[package]
name = "nappy-cat"
version = "0.1.0"
edition = "2024"

[dependencies]
cat-core = { version = "0.1.0", path = "../../crates/cat-core" }
eframe = "0.33.3"
egui = "0.33.3"
egui_extras = "0.33.3"
open = "5.4.2"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
